

public class AVL<T> : ABP<T>, IAVL<T> where T : IComparable<T>
{

    // ======================
    // Sobrescrevendo Insert
    // ======================


    // ======================
    // Sobrescrevendo Remove
    // ======================


    // ======================
    // Auxiliares AVL
    // ======================
    public int GetFatorBalanceamento(Node<T> no)
    {

    }

    public void RotacaoDuplaDireita(Node<T> no)
    {

    }

    public void RotacaoDuplaEsquerda(Node<T> no)
    {

    }

    public void RotacaoSimplesDireita(Node<T> no)
    {

    }

    public void RotacaoSimplesEsquerda(Node<T> no)
    {

    }
}